# Generated by Django 3.1 on 2023-05-04 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('teamname', models.CharField(max_length=30)),
                ('team_color', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intrams.courses')),
                ('teams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intrams.teams')),
            ],
        ),
    ]
